### ISSUE TITLE
No es la ultima versión :(

### ISSUE THREAD

**Issue by Nullpo** [prometheus-ar/vot.ar#1]
Segun la auditoria hecha por la UBA, la ultima versión es la 3.1, con lo cual algun bug o agujero de seguridad podria haberse solucionado en la versión que va a ser puesta a producción.

https://www.eleccionesciudad.gob.ar/uploads/OAT%20n%203-15-06012015204749.pdf

Pagina 9.

**Comment by prometheus-ar** [comment]
estoy haciendo algo al respecto, mañana esperá novedades.

**Comment by prometheus-ar** [comment]
listo, la versión más reciente está en la branch paso2015.
