### ISSUE TITLE
no entendí bien de donde viene esto

### ISSUE THREAD

**Issue by ghost** [prometheus-ar/vot.ar#10]
esto es filtrado? o es algo que lanzaron MSA pero en un lugar escondido? y los ISOs? etc

**Comment by luislezcair** [comment]
Es filtrado. El sitio donde subieron los ISOs solamente mantiene los archivos por 30 días, por eso ya no están disponibles.

**Comment by ghost** [comment]
Ah genial. Yo pensé que *al menos* vot.ar era codigo libre, revisable de una manera oficial. Supongo que no.
